import { MigrationInterface, QueryRunner } from "typeorm";

export class FixLabelPrintJobsTimestamptz1812000000000
  implements MigrationInterface
{
  name = "FixLabelPrintJobsTimestamptz1812000000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Convert timestamp without time zone columns to timestamptz
    // while preserving the intended instant.
    //
    // created_at / updated_at were generated by the DB with NOW()
    // in GMT (UTC), so their wall-clock values represent UTC.
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN created_at SET DATA TYPE TIMESTAMPTZ
      USING created_at AT TIME ZONE 'UTC';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN updated_at SET DATA TYPE TIMESTAMPTZ
      USING updated_at AT TIME ZONE 'UTC';
    `);

    // Lifecycle timestamps (claimed_at, lease_expires_at, completed_at,
    // failed_at) were supplied by Node running under
    // America/Argentina/Buenos_Aires, so their wall-clock values
    // represent that zone.
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN claimed_at SET DATA TYPE TIMESTAMPTZ
      USING claimed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN lease_expires_at SET DATA TYPE TIMESTAMPTZ
      USING lease_expires_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN completed_at SET DATA TYPE TIMESTAMPTZ
      USING completed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN failed_at SET DATA TYPE TIMESTAMPTZ
      USING failed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverse: convert timestamptz → timestamp without time zone,
    // preserving displayed wall-clock semantics.
    //
    // AT TIME ZONE on a timestamptz produces a timestamp without tz
    // displayed in the given zone.  Using the same zone as in up()
    // restores the original wall-clock values.
    //
    // created_at / updated_at → back at UTC wall-clock.
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN created_at SET DATA TYPE TIMESTAMP
      USING created_at AT TIME ZONE 'UTC';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP
      USING updated_at AT TIME ZONE 'UTC';
    `);

    // Lifecycle fields → back at America/Argentina/Buenos_Aires wall-clock.
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN claimed_at SET DATA TYPE TIMESTAMP
      USING claimed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN lease_expires_at SET DATA TYPE TIMESTAMP
      USING lease_expires_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN completed_at SET DATA TYPE TIMESTAMP
      USING completed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
    await queryRunner.query(`
      ALTER TABLE label_print_jobs
      ALTER COLUMN failed_at SET DATA TYPE TIMESTAMP
      USING failed_at AT TIME ZONE 'America/Argentina/Buenos_Aires';
    `);
  }
}
